# Generated by Django 4.1.1 on 2022-09-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/'),
        ),
    ]
