# Generated by Django 4.1.1 on 2022-09-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_biography_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default='avatars/default.jpeg', upload_to='avatars/'),
        ),
    ]
