# Generated by Django 4.1.1 on 2022-09-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_answer_text_alter_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
