# Generated by Django 4.1.1 on 2022-09-25 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PostAnswer', to='main.post'),
        ),
    ]
