# Generated by Django 4.1.1 on 2022-09-25 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_answer_voters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-votesUp',)},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='voters',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
        migrations.AddField(
            model_name='answer',
            name='votesDown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnswerVotesDown', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='votesUp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnswerVotesUp', to=settings.AUTH_USER_MODEL),
        ),
    ]
