# Generated by Django 4.1.1 on 2022-09-25 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_alter_answer_options_remove_answer_voters_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='votesDown',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='votesUp',
        ),
        migrations.AddField(
            model_name='answer',
            name='votesDown',
            field=models.ManyToManyField(blank=True, related_name='AnswerVotesDown', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='votesUp',
            field=models.ManyToManyField(blank=True, related_name='AnswerVotesUp', to=settings.AUTH_USER_MODEL),
        ),
    ]
