# Generated by Django 4.1.1 on 2022-09-28 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_answer_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-votes',)},
        ),
    ]
